### ISSUE TITLE
Uploading new items from queue is broken

### ISSUE THREAD

**Issue by oskarkrawczyk** [bootle/DropZone#1]
When trying to upload additional items from queue (after some items have been already uploaded), the lib throws an error `Uncaught TypeError: Cannot call method 'destroy' of null`

**Comment by bootle** [comment]
Hey Oskar,

I'm travelling at the moment, and find it hard to get online :) Back online in a week - I'll have a look at all issues then

Big thanks for reporting!

**Comment by bootle** [comment]
I just pushed an update which should resolve this issue. Thanks for reporting!
