### ISSUE TITLE
Flash uploads in IE8/9

### ISSUE THREAD

**Issue by szwagros** [bootle/DropZone#10]
Just a question about Flash upload. Is it intended behavior that after each queueComplete Swiff object is recreated ? 

I'm asking because in IE8/9, after uploading file(s) there is an error message "SetReturnValue not supported by object..."  - I don't remember exact error description but judging by where the exception is raised the error is about Flash calling JS function on Swiff object. 

But at this time this object is recreated in DropZone.Flash.reset function and has different ID - so call fails. I've fixed this by moving all initialization in DropZone.Flash from reset to activate function but I don't know if this has any side effects

**Comment by bootle** [comment]
Hi Szwagros, you are right, the reset was only necessary to re-position the flash button. I updated and t's now done in a better way, thanks!
