### ISSUE TITLE
Flash mode doesn't return anything in callback

### ISSUE THREAD

**Issue by oskarkrawczyk** [bootle/DropZone#2]
In flash mode, the `onFinishUpload` should respond with two arguments, the second being the actual response that comes from the server. Currently this argument is always `undefined`, wheres in html4/5 modes this returns the correct response.

Any ides what can be the cause of this?

**Comment by oskarkrawczyk** [comment]
Oops, this issue was supposed to be posted on MooUpload.

That said, if DropZone is based on MooUpload, it's highly probable, the same issue applies here.

**Comment by bootle** [comment]
Hey Oskar,

Sorry for getting back so late, I've been travelling through India which makes programming hard :)

Yes, MooUpload's flash callback was broken, we fixed it in DropZone though and it should work equally fine for all methods - can you confirm?

**Comment by oskarkrawczyk** [comment]
@bootle Hey, I ended up patching MooUpload, but will be migrating the scripts to use DropZone in the coming weeks, so I'll be sure to update you on the callback situation.

**Comment by bootle** [comment]
Thanks! @oskarkrawczyk
