### ISSUE TITLE
Some images in Bulk loading misses the loading-bar

### ISSUE THREAD

**Issue by heoa** [bootle/DropZone#3]
Annotated image explains more than thousand words [1]. What may cause this bug?

[1] http://koti.kapsi.fi/~he/bug_bar_missing_in_one_photo.png

**Comment by bootle** [comment]
Good question :) The demo isn't too perfect, I made it for an alpha version of the class and never had time to update properly - sorry for that! I'll try to take a look soon..

DropZone itself never fails like this though (tested by thousands of users on dropr.com now). 

I'll push an update as soon as I have a spare moment.

**Comment by heoa** [comment]
I tested it whether the functionality is broken or is it just the visual thing: the result with a few test is that it is just the visual -loading bar, otherwise the files get loaded to the tmp -dir.

Please, use the minified version here [2] -- I have killed all of the clutter properties and it contains just the DropZone. 

If you have some doubts where the bug is, please, do not hesitate to write it -- I am also interested in the line that determine the names of the files in tmp -folder. Please, let me know your ideas so I will help you because I need to get this working...

You can find me in Freenode under heoa, thanks. Do not hesitate to contact me there because I want to fix this bug :D

[2] koti.kapsi.fi/~he/d.tgz

**Comment by bootle** [comment]
I just synced an update that's been lying around for a while, it optimises things in HTML5 uploads, and possibly fixes the bug in demo, let me know if that's true. I haven't updated the demo itself though so it might still happen there - will definitely do when I get a moment! :)

**Comment by heoa** [comment]
Sorry but this [-1] did not fix the bug [0]. Updated minified example with your patches [1], no idea what they did but did not kill the bug.

**References**
[-1] https://github.com/bootle/DropZone/commit/9c3c8105e64eb2f36496cd22f7d457c7305a08fb#commitcomment-1739535
[0] https://github.com/bootle/DropZone/issues/3
[1] koti.kapsi.fi/~he/d2.tgz

**Comment by bootle** [comment]
This issue should be long gone now, although the demo code remains a very simple one :)
