### ISSUE TITLE
Downloading bars too wide, lagging and missing colors time-to-time

### ISSUE THREAD

**Issue by heoa** [bootle/DropZone#7]
The mechanism with downloading bars, usually blue, is totally broken:
1. it sometimes shows numbers
2. it is sometimes wider than the images
3. it is sometimes lagging
4. ...

I suggest full rewrite, there is more bugs related to this [1]. The code is low-quality, some comments about what each sector wants to do appreciated -- so many different uploading things and odd files, puzzling.

Simplicity before cleverness, thanks.

[1] https://github.com/bootle/DropZone/issues/3

**Comment by bootle** [comment]
Hello again.. I told you the demo is old and doesn't give justice to the class, please wait a while till we update it. Check it on dropr.com, it works perfectly there. 

I don't understand what:
1. it sometimes shows numbers

means?

The Uploader has only 5 JS files, the main class + Request.Blob extension for Request + 3 modules for each upload method (HTML5, HTML4, Flash), I don't see what is puzzling here?

You're right about the comments though, we'll improve when revising next time
