### ISSUE TITLE
Uploads doesn't work in HTML 5

### ISSUE THREAD

**Issue by szwagros** [bootle/DropZone#9]
After recent changes uploads in HTML5 are broken. Filename for saving file is created from id and name which are read from $headers variable:

$response['id']     = $headers['X-File-Id'];
$response['name']   = basename($headers['X-File-Name']);

but X-File-Id and X-File-Name are send in query string not in headers so every file is stored with "_" filename.

**Comment by bootle** [comment]
Hi there, sorry I updated the PHP part with changes from Juan and didn't test the "standalone" version of DropZone much, I simply updated the vars to use $_GET for now and the class works. I'll take another look to cleanup the thing when I have some more spare time. Thanks!
